import hashlib
m = input('Enter String to hash: ')
# Assumes the default UTF-8
h = hashlib.md5(m.encode())
print("\nmd5 hash")
print(h.hexdigest())
s=hashlib.sha1(m.encode())
print("\nsha1 hash")
print(s.hexdigest())
r=hashlib.sha224(m.encode())
print("\nsha224 hash")
print(r.hexdigest())
l=hashlib.sha256(m.encode())
print("\nsha256 hash")
print(l.hexdigest())
p=hashlib.sha384(m.encode())
print("\nsha384 hash")
print(p.hexdigest())
k=hashlib.sha512(m.encode())
print("\nsha512 hash")
print(k.hexdigest())